spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/management?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    schema: database/import.sql
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false
    mode: LEGACYHTML5


favorites:
  base:
    path: templateshttp://127.0.0.1:8080/



